name: Heuristic Lender Reply Checker

on:
  schedule:
    - cron: '*/20 * * * *'  # Run every 20 minutes
  workflow_dispatch:         # Allow manual trigger in GitHub UI

jobs:
  heuristic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run heuristic reply checker
        run: node runHeuristicReplyCheck.js
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
